### ISSUE TITLE
the algorithm  doesn't converge  

### ISSUE THREAD

**Issue by h1063135843** [yblin/global_l0#2]
The program works well in some situation. But when I attempt to detect planes in some bigger pointclouds, the program  seems to be stuck in a endless loop and I can't have a result. Does the algorithm  always converge?

**Comment by h1063135843** [comment]
![image](https://user-images.githubusercontent.com/26903569/101011528-94f2a680-359d-11eb-982a-673da8bdd56c.png)
I print the subset size after each iteration, and the size doesn't decrease to meet the breaking condition. On the contrary it always increase.

**Comment by yblin** [comment]
Strange problem, can you send me the data

发件人：duan-she-li <notifications@github.com>
发送日期：2020-12-03 19:29:36
收件人：yblin/global_l0 <global_l0@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re: [yblin/global_l0] the algorithm doesn't converge (#2)


I print the subset size after each iteration, and the size doesn't decrease to meet the breaking condition. On the contrary it always increase.

**Comment by h1063135843** [comment]
> Strange problem, can you send me the data 发件人：duan-she-li <notifications@github.com> 发送日期：2020-12-03 19:29:36 收件人：yblin/global_l0 <global_l0@noreply.github.com> 抄送人：Subscribed <subscribed@noreply.github.com> 主题：Re: [yblin/global_l0] the algorithm doesn't converge (#2) I print the subset size after each iteration, and the size doesn't decrease to meet the breaking condition. On the contrary it always increase. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply. Finally the program works well, and it is just too slow  in my case(18 hours). The subset size always increases firstly. Increasing the number of min support points will accelerate the process for big pointcloud. Furthermore, computing distance2 in the metric function also cost too much time. I am curious about it whether it is the same as the rmsn metric mentioned in  your article.

**Comment by yblin** [comment]
Do you mean RMSE? I think it is the same

**Comment by yblin** [comment]
> Thanks for your reply. Finally the program works well, and it is just too slow in my case(18 hours). The subset size always increases firstly. Increasing the number of min support points will accelerate the process for big pointcloud. Furthermore, computing distance2 in the metric function also cost too much time. I am curious about it whether it is the same as the rmsn metric mentioned in your article.

Do you mean RMSE? I think it is the same
